# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-28 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('head', models.FileField(upload_to='account/user/zhangsan/%Y%m%d')),
            ],
        ),
    ]
